In [1]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical 
# operations?

In [3]:
# Purpose and Advantages:

# 1.Efficient Numerical Operations: NumPy's arrays are optimized for numerical computations, offering a vast array of functions and operations 
# for performing mathematical operations on arrays, such as element-wise addition, subtraction, multiplication, division, and more. 

# 2.Broad Range of Functions: NumPy provides a comprehensive set of mathematical functions, including trigonometric functions, logarithmic 
# functions, exponentials, and statistical functions.

# 3.Memory Efficiency: NumPy's arrays are stored in contiguous memory blocks, improving memory access patterns and reducing memory overhead 
# compared to Python lists.

# How NumPy Enhances Python's Capabilities:

# Speed and Performance: NumPy's optimized array operations and efficient memory management significantly improve the speed of numerical 
# computations compared to Python's built-in data structures.

# Concise and Readable Code: NumPy's array-based syntax and vectorized operations allow for writing concise and readable code, making it easier 
# to express mathematical formulas and algorithms.

# Integration with Scientific Computing Ecosystem: NumPy's integration with other scientific Python libraries enables a powerful and versatile 
# environment for data analysis, machine learning, and scientific research.

In [5]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
# other?

In [7]:
# np.mean():
# Simple mean: Calculates the arithmetic mean of an array, which is the sum of all elements divided by the number of elements.
# Weights not supported: Doesn't allow for specifying weights for individual elements.

# np.average():
# Weighted mean: Can calculate the weighted average of an array, where each element is multiplied by its corresponding weight before summing and 
# dividing by the sum of weights.Default weights: If no weights are provided, it defaults to equal weights for all elements, making it equivalent 
# to np.mean().

# When to use which:
# np.mean(): Use when you want to calculate the simple arithmetic mean of an array and don't need to assign weights to individual elements.
# np.average(): Use when you want to calculate a weighted average, where some elements should contribute more or less to the overall average.
# This is common in statistics and data analysis when dealing with data that has different levels of importance or uncertainty.

In [9]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
# arrays.

In [11]:
# NumPy provides the flip() function to reverse an array along specified axes.

# for 1-D array
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = np.flip(arr1d)
print(reversed_arr1d)

# Explanation:
# In a 1D array, np.flip() simply reverses the order of the elements.

[5 4 3 2 1]


In [13]:
# for 2-D array
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Reverse along the first axis (rows)
reversed_rows = np.flip(arr2d, axis=0)
print(reversed_rows) 

[[4 5 6]
 [1 2 3]]


In [15]:
# Reverse along the second axis (columns)
reversed_cols = np.flip(arr2d, axis=1)
print(reversed_cols)

[[3 2 1]
 [6 5 4]]


In [17]:
# Reverse along both axes
reversed_both = np.flip(arr2d)
print(reversed_both)

[[6 5 4]
 [3 2 1]]


In [19]:
# Explanation:
# In a 2D array:
# axis=0 reverses the rows, so the first row becomes the last and vice versa.
# axis=1 reverses the columns, so the first column becomes the last and vice versa.
# If axis is not specified (or None), both rows and columns are reversed.

In [21]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
# in memory management and performance.

In [23]:
# NumPy provides the dtype attribute to access the data type of elements in an array. This attribute returns a numpy.dtype object that represents 
# the data type.

# Here's an example:

In [25]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [27]:
# Importance of Data Types in Memory Management and Performance

# Data types play a crucial role in memory management and performance in NumPy arrays:

# Memory Management:
# Efficient Storage: NumPy arrays are stored in contiguous memory blocks, and the data type determines the size of each element. Choosing the 
# appropriate data type can significantly reduce memory usage, especially for large datasets.

# Data Integrity: Using the correct data type ensures that data is stored and interpreted correctly. For example, storing integer values in a 
# floating-point data type might lead to precision errors.
    
# Performance:
# Optimized Operations: NumPy's operations are often optimized for specific data types. Using the correct data type can result in faster 
# computations.

# Memory Access Patterns: The data type affects how elements are accessed in memory. Using a data type that aligns well with the hardware's 
# memory architecture can improve performance.

In [29]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [31]:
# NumPy ndarrays (N-dimensional arrays) are the fundamental data structure in NumPy. They are multidimensional arrays of homogeneous data type, 
# optimized for numerical operations. This means all elements in an ndarray must be of the same data type (e.g., int, float, bool).

# Key Features:
# Homogeneous Data Type: All elements in an ndarray must be of the same data type, ensuring efficient memory layout and optimized operations.

# Multidimensional: ndarrays can have any number of dimensions, from 0D (scalar) to higher-dimensional arrays like matrices and tensors.

# Optimized Operations: NumPy provides a vast array of functions and operations that are highly optimized for ndarrays, allowing for efficient 
# numerical computations on large datasets.

# Indexing and Slicing: Powerful indexing and slicing mechanisms enable easy access to and manipulation of elements within ndarrays.



# Differences from Standard Python Lists:
# Homogeneity: Python lists can contain elements of different data types, while ndarrays require all elements to be of the same type.

# Performance: ndarrays are significantly faster for numerical operations than Python lists, especially for large datasets, due to their 
# optimized memory layout and vectorized operations.

# Fixed Size: Python lists can be dynamically resized, while ndarrays have a fixed size.

In [33]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

In [35]:
# NumPy arrays offer significant performance advantages over Python lists when dealing with large-scale numerical operations. This is primarily due 
# to the following factors:
# 1. Homogeneous Data Type: NumPy arrays store elements of the same data type in contiguous memory blocks, allowing for more efficient memory 
# access and arithmetic operations.

# 2. Fixed Size: NumPy arrays have a fixed size, allowing for efficient memory allocation and deallocation. This avoids the overhead of dynamic 
# resizing that can occur with Python lists.

# 3. C-Based Implementation: NumPy is implemented in C, providing direct access to low-level memory operations and system calls. This enables it to 
# perform computations more efficiently than Python's interpreted code.

In [37]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
# output.

In [39]:
# Both vstack() and hstack() are functions used to stack NumPy arrays vertically or horizontally, respectively.

In [41]:
# vstack(): Vertical Stacking
# Purpose: Stacks arrays vertically, meaning the arrays are stacked one on top of another.
# Requirements: The arrays must have the same number of columns.

# Example:
array1 = np.array([[1, 2],
                  [3, 4]])
array2 = np.array([[5, 6],
                  [7, 8]])

stacked_array = np.vstack((array1, array2))
print(stacked_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
# hstack(): Horizontal Stacking
# Purpose: Stacks arrays horizontally, meaning the arrays are stacked side by side.
# Requirements: The arrays must have the same number of rows.

# Example:
array1 = np.array([[1, 2],
                  [3, 4]])
array2 = np.array([[5, 6],
                  [7, 8]])

stacked_array = np.hstack((array1, array2))
print(stacked_array)

[[1 2 5 6]
 [3 4 7 8]]


In [45]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# array dimensions.

In [47]:
# Both fliplr() and flipud() are functions used to flip NumPy arrays along specific axes:

In [49]:
# fliplr(): Flip Left-Right
# Purpose: Flips the array along the left-right axis (the second axis in a 2D array).
# Effect: Reverses the order of columns in a 2D array.

# Example:
array = np.array([[1, 2, 3],
                 [4, 5, 6]])

flipped_array = np.fliplr(array)
print(flipped_array)

[[3 2 1]
 [6 5 4]]


In [51]:
# flipud(): Flip Up-Down
# Purpose: Flips the array along the up-down axis (the first axis in a 2D array).
# Effect: Reverses the order of rows in a 2D array.

# Example:
array = np.array([[1, 2, 3],
                 [4, 5, 6]])

flipped_array = np.flipud(array)
print(flipped_array)

[[4 5 6]
 [1 2 3]]


In [53]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [57]:
# The array_split() function in NumPy is used to split an array into a specified number of sub-arrays. The splitting is done along the first axis 
# (rows) by default.
# Syntax: np.array_split(ary, sections, axis=0), where ary: The array to be split, sections: The number of sub-arrays to create, axis: The axis along which to split the array (default is 0).

In [59]:
# Example:
arr = np.arange(10)
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [61]:
# Handling Uneven Splits:
# If the number of elements in the array is not evenly divisible by the number of sections, the array_split() function will distribute the extra 
# elements to the first few sub-arrays.

In [63]:
# Example:
arr = np.arange(11)
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]


In [65]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
# operations?

In [67]:
# Vectorization and broadcasting are two fundamental concepts in NumPy that significantly contribute to efficient array operations.

# Vectorization:
# Vectorization refers to the ability to perform operations on entire arrays or matrices element-wise without the need for explicit loops. This 
# is achieved by NumPy's optimized underlying implementations, which can leverage SIMD instructions and other hardware-specific optimizations.

# Benefits of Vectorization:

# Speed: Vectorized operations are typically much faster than equivalent Python loops, especially for large arrays.
# Readability: Vectorized code is often more concise and easier to understand than equivalent loop-based code.
# Memory Efficiency: Vectorized operations can often be more memory efficient than loop-based approaches, especially when dealing with large 
# arrays.

In [69]:
# Example:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Vectorized addition
result = x + y
print(result)

[5 7 9]


In [71]:
# Broadcasting

# Broadcasting is a mechanism in NumPy that allows arrays of different shapes to be compatible for element-wise operations. NumPy automatically 
# stretches the smaller array to match the shape of the larger array, as long as their shapes are compatible.

# Rules for Broadcasting:

# Shape Compatibility: The arrays must have compatible shapes. This means that the trailing dimensions of the arrays must be equal, or one of 
# them must be 1.

# Stretching: If the dimensions of the arrays are not equal, the smaller array is stretched to match the larger array by replicating elements 
# along the missing dimensions.

In [73]:
# Example:
x = np.array([1, 2, 3])
y = np.array([[4],
              [5],
              [6]])

# Broadcasting
result = x * y
print(result)

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [75]:
# Both vectorization and broadcasting contribute to efficient array operations in NumPy by:
# Reducing computational overhead: By eliminating explicit loops and leveraging optimized implementations, vectorization and broadcasting can 
# significantly reduce computational overhead.

# Improving memory access patterns: NumPy's memory layout and optimized algorithms can improve memory access patterns, leading to faster execution 
# times.

# Simplifying code: Vectorized and broadcasting operations often result in more concise and readable code, making it easier to write and maintain.

In [77]:
# PRACTICAL QUESTION:

In [79]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [81]:
# Create a 3x3 NumPy array with random integers between 1 and 100. 
array = np.random.randint(1, 101, (3, 3))

print("Original array:")
print(array)

interchanged_array = array.T

print("Interchanged array:")
print(interchanged_array)

Original array:
[[81 30 66]
 [97 22 65]
 [21 31 86]]
Interchanged array:
[[81 97 21]
 [30 22 31]
 [66 65 86]]


In [83]:
# Explanation for np.random.randint(1, 101, (3, 3)):
# np.random.randint: This is a NumPy function used to generate random integers.

# 1: This is the lower bound for the random integers. The generated numbers will be greater than or equal to 1.
                          
# 101: This is the upper bound for the random integers. The generated numbers will be less than 101.
                            
# (3, 3): This is the shape of the array you want to create. It specifies the number of rows and columns. In this case, you're creating a 3x3 
# array.

In [85]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [87]:
array = np.arange(10)
array_2x5 = array.reshape(2, 5)
array_5x2 = array.reshape(5, 2)

print("Original array:", array)
print("Reshaped 2x5 array:", array_2x5)
print("Reshaped 5x2 array:", array_5x2)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reshaped 2x5 array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 5x2 array: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [89]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [91]:
array = np.random.rand(4, 4)

# Add a border of zeros around it
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print("Original array:")
print(array)

print("Array with border:")
print(array_with_border)

Original array:
[[0.29777824 0.87601595 0.65288149 0.21555792]
 [0.00133229 0.63717841 0.01686752 0.32589177]
 [0.93696177 0.23916302 0.02930147 0.18728765]
 [0.16223723 0.73257384 0.86356821 0.01731026]]
Array with border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.29777824 0.87601595 0.65288149 0.21555792 0.        ]
 [0.         0.00133229 0.63717841 0.01686752 0.32589177 0.        ]
 [0.         0.93696177 0.23916302 0.02930147 0.18728765 0.        ]
 [0.         0.16223723 0.73257384 0.86356821 0.01731026 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [93]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [95]:
array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [97]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) 
# to each element.

In [99]:
x = np.array(['python', 'PHP', 'java', 'C++'])

print("Original Array:")
print(x)

capitalized_case = np.char.capitalize(x)

lowered_case = np.char.lower(x)

uppered_case = np.char.upper(x)

titlecased_case = np.char.title(x)

print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Titlecased: ", titlecased_case) 

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


In [101]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [103]:
words = np.array(['apple', 'banana', 'orange'])
spaced_words = np.char.join(' ', words)
print(spaced_words)

['a p p l e' 'b a n a n a' 'o r a n g e']


In [105]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [107]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

addition = array1 + array2

subtraction = array1 - array2

multiplication = array1 * array2

division = array1 / array2

print("Array 1:")
print(array1)

print("Array 2:")
print(array2)

print("Addition:")
print(addition)

print("Subtraction:")
print(subtraction)

print("Multiplication:")
print(multiplication)

print("Division:")
print(division)

Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
Multiplication:
[[ 5 12]
 [21 32]]
Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [109]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [111]:
identity_matrix = np.eye(5)

diagonal = identity_matrix.diagonal()

print("Identity matrix:")
print(identity_matrix)

print("Diagonal elements:")
print(diagonal)

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements:
[1. 1. 1. 1. 1.]


In [113]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array.

In [115]:
def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

random_numbers = np.random.randint(0, 1001, 100)

prime_numbers = [num for num in random_numbers if is_prime(num)]

print("Random numbers:", random_numbers)
print("Prime numbers:", prime_numbers)

Random numbers: [885 425 471  19 618 595 335 389 670 629 809  57 420 755 200 590 760 732
 421 316 324 830 576 628 554 252 923 115 905 447 577  49 163 495 302 705
 998 581 732 273 292 636 823 220 405 336   8 337 751 701 520 180 745 337
  53 196 165 169 717 673 279 323 608 936 939 609 553 545 345  25 237 811
 826 358 634 361 398 226 825  88 736 237 655 147 247 356  47 141 548 898
 887 874 958 917 833 359 153 778 338 951]
Prime numbers: [19, 389, 809, 421, 577, 163, 823, 337, 751, 701, 337, 53, 673, 811, 47, 887, 359]


In [117]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages.

In [119]:
daily_temperatures = np.array([72, 75, 73, 78, 80, 82, 85, 87, 86, 84, 83, 81, 79, 77, 76, 74, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 90, 88, 86, 84])

# Remove the last 2 elements to make the total number of elements divisible by 7 since the total number of elements in the array is 30, which cannot be evenly divided into 28 elements (4 rows * 7 columns).
daily_temperatures = daily_temperatures[:-2]

# Calculate weekly averages
weekly_averages = np.mean(daily_temperatures.reshape(4, 7), axis=1)

print("Daily temperatures:", daily_temperatures)
print("Weekly averages:", weekly_averages)

Daily temperatures: [72 75 73 78 80 82 85 87 86 84 83 81 79 77 76 74 73 75 77 79 81 83 85 87
 89 91 90 88]
Weekly averages: [77.85714286 82.42857143 76.42857143 87.57142857]
